package com.hefesto.juntasaccioncomunal.logica.componentes.login.repositorios

interface LoginSharedPreferencesDatasource

class LoginSharedPreferencesDatasourceImpl : LoginSharedPreferencesDatasource {
}